apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-printer
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date-printer
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Yeah!
          restartPolicy: OnFailure
